### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by xmnlab** [thegraphnetwork/wave-docker-template#1]
ERROR: Could not find a version that satisfies the requirement h20-wave (from versions: none)
ERROR: No matching distribution found for h20-wave

[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: pip install --upgrade pip

**Comment by esloch** [comment]
@xmnlab, I think this is resolved here #3  , can we close this issue?

**Comment by xmnlab** [comment]
Sounds good. Thanks!!
